=== nfultz/codetrack/users.dtd
<!--  Document Type Definition for CodeTrack Users XML Database  -->
<!--                                                             -->
   <!ELEMENT users (user+)>
      <!ELEMENT user (ID, First_Name, Last_Name, Full_Name, Initials, Username, Email,
                      Phone, Role, Password) >
            <!ELEMENT ID                  (#PCDATA)>
            <!ELEMENT First_Name          (#PCDATA)>
            <!ELEMENT Last_Name           (#PCDATA)>
            <!ELEMENT Full_Name           (#PCDATA)>
            <!ELEMENT Initials            (#PCDATA)>
            <!ELEMENT Username            (#PCDATA)>
            <!ELEMENT Email               (#PCDATA)>
            <!ELEMENT Phone               (#PCDATA)>
            <!ELEMENT Role                (#PCDATA)>
            <!ELEMENT Password            (#PCDATA)>

=== nfultz/codetrack/xml/users.xml
<?xml version="1.0" ?>
<!--  Users database for CodeTrack.  Edit at your own risk.    -->
<!--  Meaning: re-check for XML well-formedness and validity!  -->
<!DOCTYPE users SYSTEM "users.dtd">
<users>
	<user>
		<ID>0000</ID>
		<First_Name>System</First_Name>
		<Last_Name>Admin</Last_Name>
		<Full_Name>System Admin</Full_Name>
		<Initials>SA</Initials>
		<Username>admin</Username>
		<Email>codetrack@localhost</Email>
		<Phone>555-123-4567</Phone>
		<Role>Admin</Role>
		<Password>b4AtQZ1yRkFwo</Password>
	</user>
</users>
